### ISSUE TITLE
US 2022 - LICENSE

### ISSUE THREAD

**Issue by aaehmann** [pharmaverse/pharmaverse.workshop.phuseUS2022#2]
Hi @rossfarrugia  -
Please confirm license has not changed since PHUSE EU.  I copied the file from the original folder.

**Comment by rossfarrugia** [comment]
@aehmann-gsk could just change the date there to 2022 but dont think it matters too much as it's permissive and all open. i only added the license last time more as a formality to protect us. 

@mstackhouse any pressing need to have Atorus added on the license file here given you're helping Tad, Alice and Robin with developing these US workshop hands-on exercises?

**Comment by mstackhouse** [comment]
@rossfarrugia  I have no strong feelings about this.

**Comment by aaehmann** [comment]
Year is updated.  I will close this issue as I think we are all set with this file.
